### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Number11111** [XuelianCheng/SLT-Net#1]
请问一下为什么CAD2016的groundtruth图很多是全黑的呢

**Comment by XuelianCheng** [comment]
Hi, 

The original ground-truth maps were labelled as 1/2 index for each pixel. You need to transfer it as 0/255. We also provide the transformed new gt [here](https://drive.google.com/file/d/1LwswF3axQ0BSC6DllTpyL77Ktruy-6M6/view?usp=sharing) for ease.

**Comment by XuelianCheng** [comment]
Hi,

The original ground-truth maps were labelled as 1/2 index for each pixel. You need to transfer it as 0/255. We also provide the transformed new gt [here](https://drive.google.com/file/d/1LwswF3axQ0BSC6DllTpyL77Ktruy-6M6/view?usp=sharing) at your ease.

**Comment by Number11111** [comment]
非常感谢！还有请问一下您在训练的时候有用到您提供的伪标签吗？

**Comment by XuelianCheng** [comment]
We provide results with and without our pseudo label. Please check the paper.

**Comment by clelouch** [comment]
我有一些不太明白，CAD数据集frog——frog_030.png对应的gt也是全黑的，并且我用opencv读取之后发现是一个全0的黑图。然而RGB输入图像里面青蛙还在图像中，我不理解为什么gt里面没有显示
